### ISSUE TITLE
Wrong status

### ISSUE THREAD

**Issue by ghost** [rsiebert/TVHClient#233]
Hi
I found next issue. When i wathc on transmision programm and click on start recording. Recording program which is now transmision. In android show me info that Recordings will starts in 15 minutes. But recordings in starts now. 
This info should be only show to scheduled recording. 

For now recording should show Recordings is now recording or some other...

**Comment by rsiebert** [comment]
Thanks for the info. I have found the issue

**Comment by ghost** [comment]
Ok waiting for update...
25.04.2016 9:16 PM "Robert Siebert" notifications@github.com napisał(a):

**Comment by rsiebert** [comment]
Fixed in https://github.com/rsiebert/TVHClient/commit/7cc467534383996634b789c81a2dccc61e972ad9

**Comment by ghost** [comment]
can you build new version to i can test it ?

**Comment by ghost** [comment]
i update to latest tvhclient and problem was not resolved. Still show info that program will be recording for 15 min.

**Comment by rsiebert** [comment]
Can you send screenshots and what you did? Except the problem I fixed I can't reproduce your problem, or I don't fully understand it.

**Comment by ghost** [comment]
Ok
Looks on screen. Programm "CASTLE 5" is from 08:20 to 9:20. I click on recording this programm at 09:05 and on task bar show me notification that programm will start recording for 15 minuts. It is not true becuase recording is now. Not scheduld. Do you understand ?

![screenshot_20160505-090524](https://cloud.githubusercontent.com/assets/16692223/15038121/5f2f6548-12a1-11e6-9a5d-52e2b16b01ba.png)
![screenshot_20160505-090538](https://cloud.githubusercontent.com/assets/16692223/15038124/6238a038-12a1-11e6-9acb-55c628939195.png)

**Comment by rsiebert** [comment]
Now I get it, You meant the notifications in the statusbar. I'll look into it.

**Comment by rsiebert** [comment]
Notifications will only be shown for recordings that start om the future, not right away. See https://github.com/rsiebert/TVHClient/commit/9d42da0a99cef36494a4d1906f065fe05522123c.

**Comment by ghost** [comment]
ok share new version to test...

**Comment by rsiebert** [comment]
New beta version is out.
