### ISSUE TITLE
Version 2.0.0 no EPG info

### ISSUE THREAD

**Issue by juergen008** [rsiebert/TVHClient#402]
Since the update to 2.0.0 the program doesn't show EPG. My tvheadend version is 4.0.8

**Comment by rsiebert** [comment]
What happens when the database gets cleared from the advanced settings? It should show in the first screen that program guide data is being received.

**Comment by rsiebert** [comment]
The app will also only fetch new epg data if the last sync time was a certain time span ago. The time span is defined in the advanced settings -> sync duration of epg data. This can be either be reduced to fetch data sooner or reconnecting to the server from the toolbar menu or clearing the database will fetch new program data.

**Comment by juergen008** [comment]
After database gets cleared from the advanced settings it shows for a short time (1/4 second), first "Speichere empfangene Daten" second "Speichere empfangene Senderlogs"

**Comment by juergen008** [comment]
The  time span is one hour.

**Comment by rsiebert** [comment]
Should be fixed in the last beta 2.0.0-135

**Comment by rsiebert** [comment]
Hi Jürgen,

It should work again with the latest version 2.0.0-135.

Best regards
Robert


Am Sa., 5. Jan. 2019, 18:48 hat juergen008 <notifications@github.com>
geschrieben:

**Comment by CodeMonkeyUK** [comment]
2.0.0-135 installed and still not working. Reset db and changed all config I can think to. Even reinstalled but still no epg downloaded.

Worked great before v2.

Tvheadend has epg and recordings are scheduling and recording correctly so pretty convinced it's this client app at fault.

**Comment by rsiebert** [comment]
Hi, ist the version 2.0.0-139 working?

Am Mo., 14. Jan. 2019, 19:37 hat CodeMonkeyUK <notifications@github.com>
geschrieben:

**Comment by CodeMonkeyUK** [comment]
Sorry i got version wrong... I'm using 2.0.0 (138)

Latest beta available through Google play atm

**Comment by rsiebert** [comment]
Just as a question. The channel list is also not showing any currently running programs? The status screen shows zero programs?

**Comment by CodeMonkeyUK** [comment]
Correct

**Comment by rsiebert** [comment]
Can you send me a debug log please?

**Comment by CodeMonkeyUK** [comment]
done 2 emails 2 logs ... hopefully that helps

**Comment by rsiebert** [comment]
I have uploaded a new beta 2.0.0-140. 
Please test this one and kindly provide the logfiles.

**Comment by CodeMonkeyUK** [comment]
2.0.0-140 same behaviour... emailed you logs

Hope that helps

**Comment by rsiebert** [comment]
Lets see if the 2.0.0-141 changes something.

**Comment by CodeMonkeyUK** [comment]
Latest version installed, reset db and it now seems to have syncd.

Some channels are missing epg but I'm pretty sure that's a server issue.

Thanks for the quick fix

**Comment by rsiebert** [comment]
Good to know. The issue was only a one liner. Thanks for the support!

**Comment by CodeMonkeyUK** [comment]
No problem...

Noticed high battery usage from the app since updating to the latest
version.
(Only mention it because i noticed you'd change the EPG sync to use
background threads...)

May just be me poking/hammering it to get things working ...
i'll monitor over next few days and let you know if it is an issue.


Shaun

**Comment by rsiebert** [comment]
Regarding the battery issue. Please open another ticket if this is still the case.
