### ISSUE TITLE
Custom language sometimes not applied (or partially applied)

### ISSUE THREAD

**Issue by virtualdj** [rsiebert/TVHClient#425]
I'm using TVHClient on Android 8.1 and I noticed a problem that I saw on other apps that provide custom language selection (such as Tasker).

My OS is set in Italian but I would like to have TVHClient (and Tasker) in English, so I set it with the settings. Unfortunately, when switching back and forth other apps sometimes the strings are displayed in Italian. You can see on the screenshot below:

![tvhclient_language](https://user-images.githubusercontent.com/3251704/53695088-a0f17900-3db7-11e9-86ed-8e492c25cfcd.png)

The snackbar [2] is always displayed in Italian (wrong) while the UI normally is in English (correct). But if I switch to other apps and the activity is resumed/reloaded, part of the UI is displayed in Italian [4] again even though I didn't change the settings.
I also saw the side menu in Italian a couple of times, but I was unable to screenshot in that occasion.

May be this problem related to [this StackOverflow issue](https://stackoverflow.com/questions/47165311/how-to-change-android-o-oreo-api-26-app-language)? Please also see [this page](https://gunhansancar.com/change-language-programmatically-in-android/).
It's quite annoying to have this behaviour; I can capture logs if needed, just let me know!

**Comment by rsiebert** [comment]
Can you try this version? It should solve the language problem.
[2.2.2-155](https://drive.google.com/open?id=1kaAR6fgpbVyjSsu8ZW94BbyYvcjaWrGd)

**Comment by virtualdj** [comment]
> Can you try this version? It should solve the language problem.

A lot of better, but still not perfect. I mean, now it's **quite difficult to reproduce** the issue but unfortunately for you :smile: I found a way:

1. Enable rotation on Android quick-settings
2. Run TVHClient and check the overflow menu: it's shown correctly in English.
3. Push the task switch button to open the multitasking.
4. Rotate the screen back and forth **when in multitasking** (otherwise it works ;-)
5. Touch TVHClient to return to the app
6. Open the overflow menu... now it's in Italian! (wrong)

[Video attachment](https://github.com/rsiebert/TVHClient/files/2927655/TVHClient_Language.zip)

**Comment by rsiebert** [comment]
I have changed the locale setting according to your second link. The problem should be solved
[Version 2.2.2-156](https://drive.google.com/open?id=1Bq0XOCdLMoA6N4A_okXmEJtZKtqUeGu1)

**Comment by virtualdj** [comment]
> The problem should be solved

Mmm, the overflow menu is OK now but the snackbar still is not...

![snackbar](https://user-images.githubusercontent.com/3251704/53912608-948c4b00-4059-11e9-997e-43fa4df23973.png)

**Comment by virtualdj** [comment]
Just FYI the wrong language on the Snackbar is still present on v2.2.3 (158).

**Comment by Flole998** [comment]
Default setting is not working for me either, my device is set to German but tvhclient is English. Setting language manually to German works though.

**Comment by virtualdj** [comment]
For me Default setting works correctly (Italian) while English appears in English everywhere but the Snackbar (still in Italian).

Did you try the versions above?

**Comment by Flole998** [comment]
I can't install them as I am already on a newer version (2.2.5 162).

**Comment by rsiebert** [comment]
Can you try the version [2.2.16-176](https://drive.google.com/open?id=1TuRbAdhAfIp8_tpfqT4CXpYBs2XHRIJ8). Maybe it solves the issue?

**Comment by virtualdj** [comment]
Unfortunately that version doesn't solve: the **snackbar** messages are still in Italian (with English language chosen in the settings) and if I'm not wrong also the **Change log** is in Italian.

![Screenshot_20190812-164057_TVHClient](https://user-images.githubusercontent.com/3251704/62875159-cdc09980-bd22-11e9-9985-ff84db229367.jpg)

**Comment by rsiebert** [comment]
Is this still an issue with the [2.2.22-184](https://drive.google.com/open?id=1Ff3JzX7D9NtlzOhMBXVAKlTCJ3HstEWH) version?

**Comment by virtualdj** [comment]
> Is this still an issue with the [2.2.22-184](https://drive.google.com/open?id=1Ff3JzX7D9NtlzOhMBXVAKlTCJ3HstEWH) version?

Yes, it is. After updating/installing, the **_first_ Change log** is displayed with an Italian title with a blank text (the blank text issue always existed, but I never posted feedback about that... it "loads" indefinitely):

![1](https://user-images.githubusercontent.com/3251704/66501318-7ab95780-eac3-11e9-9117-df0172dbf759.png)

Then the application runs correctly in English (my chosen language) **except the snackbar messages**:

![2](https://user-images.githubusercontent.com/3251704/66501413-ac322300-eac3-11e9-8bd8-27766b203923.png)

If I go into the Change log section manually, then it's correctly displayed in English.

![3](https://user-images.githubusercontent.com/3251704/66501488-cc61e200-eac3-11e9-8295-be286a7908fe.png)

**Comment by virtualdj** [comment]
FYI: with the latest v2.3.5 (on the Play Store) the issue is still present.

**Comment by rsiebert** [comment]
I used the approaches described by google. No time to further investigate this issue.
