### ISSUE TITLE
Disabling times for Autorec doesn't work

### ISSUE THREAD

**Issue by Flole998** [rsiebert/TVHClient#488]
I enabled the recording times on an Autorec and now I tried to disable the recording times again so I unchecked the option, saved it but when I edit it again it is selected again.

**Comment by rsiebert** [comment]
Here is an intermediate version [2.3.5-198](https://drive.google.com/open?id=1y7scLqAXUl8Jjdp7H1uaBhjUiXsB4ZVf). This should fix the issue.

**Comment by Flole998** [comment]
Unfortunately it still doesn't work, at least for a series recording. When I remove the checkmark again it's still active when I edit it again. Also the overview still shows the times that should be gone.

**Comment by rsiebert** [comment]
Here is a test version [2.3.5-199](https://drive.google.com/open?id=1jw4Y-Ksa37RVD7JSjriMwcxW0LDt85FO) that should fix that. Please test it.

**Comment by Flole998** [comment]
Fixed, thanks. There is a message at the bottom though that a recording was deleted and created, is this wanted?

**Comment by rsiebert** [comment]
This is due to the fact that the series recording is deleted and then added as a new one.
Somehow the server does not support updating the times. So its easier to delete and readd. I will fix te message though.
