### ISSUE TITLE
Cannot build: cannot find symbol class TimerRecordingEntity

### ISSUE THREAD

**Issue by grago** [rsiebert/TVHClient#506]
Hello, i'm trying to build the project, but i'm getting the following error:

cannot find symbol class TimerRecordingEntity data/build/tmp/kapt3/stubs/debug/org/tvheadend/data/db/AppRoomDatabase.java:5: error: cannot find symbol

What could be wrong? Thanks!

**Comment by rsiebert** [comment]
I need to push the latest changes to github. Then doing a rebuild of the project should work.

**Comment by grago** [comment]
Oh nice, thanks! I'll try it once you do.

**Comment by rsiebert** [comment]
Latest changes were pushed. Should work now

**Comment by grago** [comment]
For some reason, i'm still getting:

```error: cannot find symbol
@androidx.room.Database(entities = {TimerRecordingEntity.class, SeriesRecordingEntity.class, org.tvheadend.data.entity.RecordingEntity.class, org.tvheadend.data.entity.ProgramEntity.class, org.tvheadend.data.entity.ChannelEntity.class, org.tvheadend.data.entity.ChannelTagEntity.class, org.tvheadend.data.entity.TagAndChannelEntity.class, org.tvheadend.data.entity.ConnectionEntity.class, org.tvheadend.data.entity.ServerProfileEntity.class, ServerStatusEntity.class}, exportSchema = false, version = 14)
                                    ^
  symbol: class TimerRecordingEntit
```

after pulling latest changes. 

I'm on develop branch, should i switch to master? Thanks!

**Comment by rsiebert** [comment]
The develop branch is correct. Did you do a clean project and a complete rebuild?
